#配置数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zero?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    ######################### Druid连接池的配置信息  #################
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 5
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      testWhileIdle: true
      #获取连接时执行检测，建议关闭，影响性能
      testOnBorrow: false
      #归还连接时执行检测，建议关闭，影响性能
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
          url-pattern: /monitor/druid/*
      #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true


xss:
  enabled: false
  excludes: 127.0.0.1
  urlPatterns:

swagger:
  #是否启用swagger，默认：true
  enabled: true
  #标题
  title: 零点框架API
  #描述
  description: 零点框架 swagger2 api。swagger参考：https://github.com/dyc87112/swagger-starter-demo
  #版本
  version: 0.0.1
  #维护人
  contact:
    name: jackie liao
    email: jackieliao001@163.com
    url: https://github.com/dyc87112/spring-boot-starter-swagger