# 项目相关配置
zero:
  # 名称
  name: zero
  # 版本
  version: 0.0.1
  # 版权年份
  copyrightYear: 2022
  # 文件路径
  profile: D:/profile/
  # 获取ip地址开关
  addressEnabled: true
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: char

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /zero-api
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare: 30

# 日志配置
logging:
  level:
    com.zero: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5


# Spring配置
spring:
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  # 监控应用的PID，启动时可指定PID路径,方便 kill，kill `cat /home/zeroAdmin/app.pid`
  pid:
    file: /home/zeroAdmin/app.pid
  redis:
    database: 12
    host: 182.254.161.54
    port: 12888
    #密码默认为空，注释即可，要添加密码，去掉注释添加就行
    password: crpower
    lettuce:
      pool: #star
        maxActive: 8
        maxWait: -1
        maxIdle: 8
        minIdle: 0 #end
    # 连接超时时间（毫秒）
    timeout: 3000
    # 默认的数据过期时间，主要用于shiro权限管理
    expire: 2592000


# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30
# Redis

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage:  com.zero.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置
  configuration:
    # 局映射器启用缓存
    cache-enabled: true
    # 允许 JDBC 支持自动生成主键
    use-generated-keys: true
    # 配置默认的执行器：可重入
    default-executor-type: reuse
    # 指定 MyBatis 所用日志的具体实现
#    log-impl:  org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
